### ISSUE TITLE
Crop

### ISSUE THREAD

**Issue by TomMettam** [quietvoid/hdr10plus_tool#39]
Hello! Thanks for your hard work.

A common workflow is to crop black borders from video.  dovi_tool supports this with a --crop switch. Is there such a thing with this tool? Or some other automated way to "crop" the metadata? Or is this not necessary with HDR10+?

**Comment by quietvoid** [comment]
There's nothing to adjust for HDR10+, it's resolution/aspect ratio agnostic.

**Comment by TomMettam** [comment]
@quietvoid  - Thanks for that clarification. If I understand correctly, HDR10+ can support spatial windows within the frame, do you know how these are defined?

**Comment by quietvoid** [comment]
They are defined in the `ProcessingWindow` struct, in the `hdr10plus` crate.

Also, they are not supported in version 1 of the HDR10+ spec, which is all of the available content today.
While they are parsed according to spec, the JSON metadata does not include the processing windows.
