### ISSUE TITLE
Support for HDR10+ Adaptive?

### ISSUE THREAD

**Issue by jerethi** [quietvoid/hdr10plus_tool#40]
Does the current version of hdr10plus_tool support [HDR10+ Adaptive](https://news.samsung.com/global/samsung-introduces-new-hdr10plus-adaptive-feature-for-better-at-home-viewing-experience)? If not, is it possible to add that support in future releases?

**Comment by quietvoid** [comment]
I don't think the metadata specification changed with the extension.
It's most likely processing at the TV, with no extra metadata.

**Comment by quietvoid** [comment]
> HDR10+ Adaptive harnesses its AI engine to analyze the viewing environment, including the lighting, brightness and even reflections using the sensors equipped on the TV.
The results are then incorporated into the dynamic metadata

**Comment by ValZapod** [comment]
No, it is not up to this. Adaptive is ambient light managmant. Like for SDR, if you have dark room and oled 2.4 gamma with 100 nits is good enough, if you have lcd and light room well use 2.2 and 203 nits.
Same about primaries.
