### ISSUE TITLE
.hevc file extension on mac os binaries build?

### ISSUE THREAD

**Issue by rivertim** [quietvoid/hdr10plus_tool#43]
Using binaries ver hdr10plus_tool-1.2.2-x86_64-apple-darwin.tar.gz on mac os 11.6.1

Extracting json fails when using HEVC/H265 files with .mov, .mp4, .mkv extensions with command:

./hdr10plus_tool extract foo.mov -o metadata.json 

fails and returns:
Invalid input file type.

What extension is the app expecting please?
Thanks.

**Comment by quietvoid** [comment]
A raw HEVC bitstream only.
Otherwise, you have to use FFmpeg to pipe the demuxed stream to the app.

See the examples in the README.

**Comment by rivertim** [comment]
Thanks, that helped. But first, I try to use the _--verify_ command thus: 

`ffmpeg -loglevel panic -i "foo.mkv" -c:v copy -vbsf hevc_mp4toannexb -f hevc - | ./hdr10plus_tool --verify -
`

I get:

`error: Found argument '-' which wasn't expected, or isn't valid in this context`

?

**Comment by quietvoid** [comment]
You have to use `hdr10plus_tool --verify extract -`

**Comment by rivertim** [comment]
How do I inject a metadata file into an .mkv file like:

`hdr10plus_tool inject -i video.hevc -j metadata.json -o injected_output.hevc`

But using ffmpeg to pipe it like above? There isn't a 'pipe' example in the README.
Thanks.

**Comment by quietvoid** [comment]
It's not possible currently.
