### ISSUE TITLE
people argue this tool isn't reliable 

### ISSUE THREAD

**Issue by boohboot** [quietvoid/hdr10plus_tool#44]
when I offered my hybrid release using your tool he answered:
"You already asked this the other day in chatbox. hdr10plus_tool is known to corrupt the hdr10+ stream upon injection. Releases using the tool to inject hdr10+ are not allowed to be uploaded here."

What he meant was: frames are not in the correct order. Is he right?

**Comment by quietvoid** [comment]
On extraction, metadata is reordered to presentation order.
On injection, metadata is added to the appropriate frame, again in presentation order and not decoded order.

`hdr10plus_tool` can inject into a different ordered stream and extract back identical order.

They're welcome to open an issue with a reproducible test case where `hdr10plus_tool` is wrong.
