### ISSUE TITLE
cli on ubuntu

### ISSUE THREAD

**Issue by ejadams13** [quietvoid/hdr10plus_tool#45]
i'm having an issue running this on ubuntu headless server, no issue in windows cli, any help would be appreciated. ubuntu cli states command not found even when running command inside the hdr10plus_tool directory.

thnx

**Comment by quietvoid** [comment]
Either download the precompiled binary from the releases: https://github.com/quietvoid/hdr10plus_tool/releases/tag/1.2.2
Or build the project yourself using Rust; https://www.rust-lang.org/tools/install

**Comment by ejadams13** [comment]
thnx quietvoid, it was my mistake on the binary and path

thnx again for the quick response and all the great tools you build for us!
