### ISSUE TITLE
can HDR10+ be applied to retail bluray?

### ISSUE THREAD

**Issue by boohboot** [quietvoid/hdr10plus_tool#46]
lets say I have dynamic metadata from streaming services and I want to inject it to a bluray version. can I just do it? or the mastering needs to be the same? for example:

bluray

  "pix_fmt": "yuv420p10le",
            "color_space": "bt2020nc",
            "color_primaries": "bt2020",
            "color_transfer": "smpte2084",
            "side_data_list": [
                {
                    "side_data_type": "Mastering display metadata",
                    "red_x": "35400/50000",
                    "red_y": "14600/50000",
                    "green_x": "8500/50000",
                    "green_y": "39850/50000",
                    "blue_x": "6550/50000",
                    "blue_y": "2300/50000",
                    "white_point_x": "15635/50000",
                    "white_point_y": "16450/50000",
                    "min_luminance": "50/10000",
                    "max_luminance": "10000000/10000"
                },
                {
                    "side_data_type": "Content light level metadata",
                    "max_content": 594,
                    "max_average": 109
					
web-dl

 "pix_fmt": "yuv420p10le",
            "color_space": "bt2020nc",
            "color_primaries": "bt2020",
            "color_transfer": "smpte2084",
            "side_data_list": [
                {
                    "side_data_type": "Mastering display metadata",
                    "red_x": "34000/50000",
                    "red_y": "16000/50000",
                    "green_x": "13250/50000",
                    "green_y": "34500/50000",
                    "blue_x": "7500/50000",
                    "blue_y": "3000/50000",
                    "white_point_x": "15635/50000",
                    "white_point_y": "16450/50000",
                    "min_luminance": "1/10000",
                    "max_luminance": "10000000/10000"
                },
                {
                    "side_data_type": "Content light level metadata",
                    "max_content": 1007,
                    "max_average": 159

Can I apply the 10+ from web? will it fit even though the mastering is different? ? will it override the base hdr?

**Comment by boohboot** [comment]
So after some experimentations it seems that if base hdr is dimmer than the web-dl's base hdr (maxcll) the effect is not visible. what ways are there to change the base hdr settings just like your tool does? (preferably without re-encdoing)

**Comment by quietvoid** [comment]
I don't know of anything that can edit HDR10 metadata.
