### ISSUE TITLE
Failure with running in CMD

### ISSUE THREAD

**Issue by GizmoDudex** [quietvoid/hdr10plus_tool#48]
Hi first, and sorry for disturbing, but I couldnt find a solution to verify a file.
With your readme saying : ffmpeg -i "input.mkv" -map 0:v:0 -c copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_tool --verify -  , does not work for me. "error from ffmpeg "Invalid argument"".
When I delete the "-" at the end of ffmpeg, it says output file is missing. I give him Test.hevc as outputfile and FFMpeg runs. 
But HDR10plustool does not show up afterwards.
I couldnt find out how to verify a file. I also tried hdr10plus_tool --verify INPUT and other ways...
Could you help me out?

Kind Regards
Gizmo

**Comment by quietvoid** [comment]
You need to specify the subcommand, in this case most likely `extract`.
Like this:

```bash
ffmpeg -i "input.mkv" -c:v copy -vbsf hevc_mp4toannexb -f hevc - | hdr10plus_tool --verify extract -
```
