### ISSUE TITLE
[Feature Request] Convert Dolby Vision metadata to HDR10+.

### ISSUE THREAD

**Issue by Hydra-Spectre** [quietvoid/hdr10plus_tool#51]
It is irritating that Samsung refuses to support HDR10+ and I loved the feature of converting HDR10+ to Dolby Vision in the sister app dovi_tool.
However, a great solution for that would be if hdr10plus_tool takes some DNA from dovi_tool to allow it to convert Dolby Vision metadata to HDR10+.

It would be especially great since HDR10+ content is becoming rarer.

**Comment by quietvoid** [comment]
See https://github.com/quietvoid/hdr10plus_tool/issues/37#issuecomment-922082485
