### ISSUE TITLE
file type validation

### ISSUE THREAD

**Issue by cartman0208** [quietvoid/hdr10plus_tool#53]
When trying to extract metadata from an m2ts file I get "Error: Invalid input file type."
If I rename the file to .hevc, the extract works fine.
After the process I have to rename the file back to .m2ts to regain the correct folder structure.
Is it possible to skip the file-type check (either in general or with an option?)
Thanks

**Comment by quietvoid** [comment]
Huh? Extracting from m2ts is not supposed to "work fine".

The files supported are only raw HEVC bitstreams, so the file extension is verified.

You should be using ffmpeg to pipe the video stream when it's in a container.
