### ISSUE TITLE
Include plotters release instead of git

### ISSUE THREAD

**Issue by StormBytePP** [quietvoid/hdr10plus_tool#61]
Recently, plotters finally have a new person able to upload to crates.io which allowed the release of 0.3.5 recently.

Is that version enough to avoid having git in the dependencies?

This is because I use offline mode when installing packages in my system and including that version instead of live one could help if that contains already the features wanted.

**Comment by quietvoid** [comment]
Thanks for noticing the new release.
We can switch to the latest release now that it has the `ab_glyph` feature.
