### ISSUE TITLE
I got this error... 

### ISSUE THREAD

**Issue by boohboot** [quietvoid/hdr10plus_tool#62]
When I tried to extract metadata I encountered this error message: "self.hdr10plus_sei_list.len() == frames.len()` (202577 vs 202576)" is there any workaround?

**Comment by quietvoid** [comment]
You can always edit the code and remove the validation here: https://github.com/quietvoid/hdr10plus_tool/blob/main/src/core/parser.rs#L249
It'll probably require `--skip-reorder` to avoid other errors.

Otherwise fix your file, it's invalid.

**Comment by end2endzone** [comment]
I have found a way to "fix" the input file when you encounter such an error. Fixing the input file is easier to me than patching hdr10plus_tool source code and releasing a temporary executable. The process is described in #63.
