### ISSUE TITLE
Error: Invalid PPS index

### ISSUE THREAD

**Issue by Anuskuss** [quietvoid/hdr10plus_tool#81]
```bash
ffmpeg -i DV.mkv -c copy video.hevc
ffmpeg -i HDR10Plus.mkv -c copy -bsf hevc_mp4toannexb -f hevc - | hdr10plus_tool extract -o metadata.json -
hdr10plus_tool inject -i video.hevc -j metadata.json -o video_hdr10plus.hevc
```

**Comment by quietvoid** [comment]
You're gonna have to provide a sample file for `video.hevc` because I can't reproduce the issue.

**Comment by Anuskuss** [comment]
Turns out I messed up because as an experiment I did
```
ffmpeg -i dv.mkv -bsf "noise=drop=between(n\,0\,23)" -c copy -y video.hevc
```
to try to cut those frames out and `hdr10plus_tool` didn't like that. I did a fresh extract and it works now. Will duplicate those frames in `metadata.json` instead of cutting the video (like you suggested in #41). Sorry for the noise.
