### ISSUE TITLE
Problem with SMPTE ST 2094 App 4, Version 0

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/hdr10plus_tool#83]
Hello!

I am having problems with HDR10+ SMPTE ST 2094 App 4, Version 0 metadata.
<br />

Starting from version [1.3.1](https://github.com/quietvoid/hdr10plus_tool/releases/tag/1.3.1) the `--skip-validation` flag was added, which allows to extract and parse ST2094-40 version 0.
And indeed it is extracted without problems, and you get a perfect json.

But the problem is when injecting those metadata, it seems that hdr10plus_tool always injects them as version 1 instead of keeping and respecting the original version (version 0 in this case).

For example:
- MediaInfo of the original source:
`HDR format: SMPTE ST 2094 App 4, Version 0, HDR10 compatible`

- MediaInfo of the video injected with HDR10+ metadata extracted from the previous source:
`HDR format: SMPTE ST 2094 App 4, Version 1, HDR10 compatible`
<br />

Would it be possible to make hdr10plus_tool not modify the version (and not modify anything in general) to get a result identical to the original source?

Thank you very much for everything!
Regards.
<br />

**P.S.**
It should be noted that in the json file the version is the correct one:
```
  "JSONInfo": {
    "HDR10plusProfile": "B",
    "Version": "0.0"
  }
```

So I would guess that the problem will be in the `inject` command and not in the json file.

**Comment by manuelrn** [comment]
The problem seems to be here:
https://github.com/quietvoid/hdr10plus_tool/blob/main/hdr10plus/src/metadata_json.rs#L325

I have tried changing 1 to 0 and then compile a new executable with cargo build --release.
And indeed the new video with this injected metadata now already appears as version 0 instead of 1.
<br />

Obviously I have done this just to test, since this is wrong because the version will always be 0 (then version 1 would convert it to version 0).

The ideal would be to make `application_version` dynamic and get that value from the metadata, instead of it always being a fixed value. But I don't know how to do it.


Best regards and thanks again!
<br />

**P.S.**
In order to test it I also needed to change 1 to 0 here, otherwise I got an error:
https://github.com/quietvoid/hdr10plus_tool/blob/main/hdr10plus/src/metadata.rs#L197
https://github.com/quietvoid/hdr10plus_tool/blob/main/hdr10plus/src/metadata.rs#L203

**Comment by quietvoid** [comment]
Version 0 is legacy and not supported by the HDR10+ LLC specification.
It shouldn't be used.

**Comment by quietvoid** [comment]
There's no good reason to support the legacy version.
