### ISSUE TITLE
Issue with HDR10Plus metadatas

### ISSUE THREAD

**Issue by xerta555** [quietvoid/hdr10plus_tool#90]
Hi

I think i discover a new bug with this amazing tool:

I have an HDR10 movie in mkv container, and another version of the same movie with HDR10+ and DV 8 metadatas.
I want to extract the metadatas from the second to inject them in the first one.

I get the following error when i try to inject HDR10Plus metadatas from JSON file into an HEVC file:
![image](https://github.com/user-attachments/assets/0d028afd-e153-47c6-812f-0e743fa02e6e)

(No problem to extract the DV metadatas with dovi tool.)

HDR10Plus tool exe file version used: 1.6.1

The mkv file is big (arround 81Gb) so i cut it by parts: 
part 1:
https://www.swisstransfer.com/d/d25979a4-c601-4813-aa9b-c8e482ba2060
https://www.swisstransfer.com/d/052f3767-3286-4844-9c69-43c1545cf7e9
part2: https://www.swisstransfer.com/d/0323847e-332b-4c31-a567-020d7af023aa

I had to compress the mkv video in 2 groups:
first part of the rar file compressed again ("archives_of_part1.part1.rar" and "archives_of_part1.part2.rar"), and the second part (part2) in just one link.

If i try to extracting the HDR10+ metadatas with last version of this tool: https://forum.doom9.org/showthread.php?t=183479 (using the DDVT_DEMUXER.cmd file), i get the error, but if i tried to extract metadatas manually with the right command line the matadatas and i get the JSON file.

The JSON file i get: https://www.swisstransfer.com/d/72e95bc0-ec37-4892-9f48-6b3e96aa2e17

Same result with other versions/releases of the same movie which also contains HDR10+ metadatas.

According to the various tests I've been able to carry out myself, the problem for me comes from the hdr10plus binary, whether it's with the very latest version or even with the penultimate version.

Thanks in advance for the investiguations.

**Comment by quietvoid** [comment]
Sounds like your file just has invalid metadata.

**Comment by xerta555** [comment]
> Sounds like your file just has invalid metadata.

But i beginning by testing the hevc file with the binary, and it tell me that it have HDR10Plus metadatas, not incorrect ones

**Comment by quietvoid** [comment]
The brightness can't be over 100 000 so something is definitely invalid.

**Comment by xerta555** [comment]
> The brightness can't be over 100 000 so something is definitely invalid. You can try using `--skip-validation`.

You see that by checking the big file or just with my screenshoot ?

>  You can try using --skip-validation.

Just checked which command i used previously, i used this argument in my command.

So do you mean that the problem is due to the master (full bluray 4K disk), or due to the encoding ?

**Comment by quietvoid** [comment]
> Just checked which command i used previously, i used this argument in my command.

Clearly if extraction only worked with `--skip-validation`, the metadata was invalid in the first place.
You didn't provide any info on the "command" you used but it should work for injecting too.

**Comment by xerta555** [comment]
Having tested all the 4K releases with HDR10+ for the same film, one worked, so I was able to extract the metadata correctly and re-inject it into another file.
My final file is therefore correctly recognised in HDR10+ and DV profile 8 and plays correctly on a non-4K screen, so I'll watch it in 4K later.

So the basic problem was indeed erroneous metadata, it's the first time this has happened to me.
